__author__ = "Femto Trader"
__copyright__ = "Copyright 2015, celles.net"
__credits__ = ["Femto Trader", "panpanpandas", "Bruno Franca", "Peter Bakker"]
__license__ = "MIT"
__version__ = "0.0.1"
__maintainer__ = "Mukesh Yadav"
__email__ = "mak.gnu@gmail.com"
__status__ = "Development"
__url__ = 'https://github.com/muke5hy/talibpy'
